apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: pod-manager
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "create", "delete"]

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-manager-binding
  namespace: default
subjects:
  - kind: User
    name: cd-sa
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-manager
  apiGroup: rbac.authorization.k8s.io

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cd-dep
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: dep-instance
    spec:
      containers:
        - name: dep-container
          image: localhost:8082/repository/devopstest/devopsschool:v1
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8443
              protocol: TCP