apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cd-dep
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: dep-instance
    spec:
      containers:
        - name: dep-container
          image: ionrepo:latest
          ports:
            - containerPort: 8083
              protocol: TCP
            - containerPort: 8443
              protocol: TCP