apiVersion: apps/v1
data:
  password: admin
  username: admin
kind: Secret
metadata:
  name: metadata-deployment
spec:
  selector:
    matchLabels:
      app: fluent-bit
  replicas: 1
  template:
    spec:
      containers:
        - name: container-java
          image: localhost:8082/repository/devopstest/devopsschool:v1
          ports:
            - containerPort: 8084
      imagePullSecrets:
          - name: regcred
