apiVersion: apps/v1
kind: Deployment
metadata:
  name: metadata-deployment
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: container-java
          image: localhost:8082/repository/devopstest/devopsschool:v1
          ports:
            - containerPort: 8084
      imagePullSecrets:
          - name: regcred
